refactor: update package config
ydataai/ydata-profiling pull request #1448
Opened 2023-09-17 19:26 UTC by vorel99

In python world, new standard for package configuration is `pyproject.toml`. So I moved all static config from `setup.py` to `pyproject.toml`.

* move all static package setup from `setup.py` to `pyproject.toml`
* add commands to `Makefile` 
    * install_dev_pandas: install all requirements for pandas development and testing
    * install_dev_spark: install all requirements for spark development and testing
    * compile: compile requirements files by package config (using `piptools`)
* update all `requirements` files with command `make compile`

2023-09-19 17:43 UTC, fabclmnt commented
Hi @vorel99 ,

once again than you for your contribution :) 

I've already requested the review from the team!

2023-09-20 15:10 UTC, vascoalramos requested changes

2023-09-20 15:12 UTC, vascoalramos commented
Hi @vorel99.

Thank you for your work in the migration to pyproject.toml
I left some change requests mostly related to the makefile and dependency options. The primary reason for most of the requests relates to keeping consistency between all of our open-source projects

2023-09-21 07:51 UTC, vascoalramos requested changes
Everything else seems fine to me. @portellaa, what do you think?

2023-09-21 07:51 UTC, vascoalramos commented on Makefile
> +	pip install -e ".[test, notebook]"
Since Pandas is always present, it makes more sense to just name it `install_test`

2023-10-09 16:54 UTC, vorel99 commented
hello,
@vascoalramos @portellaa what is the status of MR? Is there any blocker to be resolved?

2023-10-11 10:44 UTC, portellaa commented
Hi @vorel99 

Thanks for your PR.

Unfortunately we don't have the time right now to move forward with this, we kindly ask you to give us some more time.
Given the amount of the changes, it breaks some internal alignments that we will need to work with you, but right now we can't focus on this.

Sorry for this.
We will get in touch as soon as we can pick this.

Cheers

2024-06-07 18:54 UTC, vorel99 commented
Hello @fabclmnt,
would it be possible to reassign reviewers? The pull request was inactive for almost a year due to waiting for a message from one of current reviewers.

Thank you,
JC

2024-09-17 15:13 UTC, fabclmnt approved these changes

2024-09-17 15:14 UTC, fabclmnt commented
Hi @vorel99,

just reviewed the PR. The changes seem to be aligned! 

There are a few conflicting issues that need to be sorted so we can proceed with merge.

2024-09-23 12:06 UTC, vorel99 commented
Hi @fabclmnt , 
I rebased feature branch to develop. 
PR is ready for merge

2025-03-03 22:11 UTC, fabclmnt commented
Hi @vorel99 ,

sorry for the time taken, this will be included for the next release. May I ask you to update the branch and fix the conflicts once again? 

As soon as it is done we will have it merged and released.

2025-03-04 21:33 UTC, merged