Included setuptools in requirements
ydataai/ydata-profiling pull request #1619
Opened 2024-07-12 09:38 UTC by abdrysdale

Fixes #1618 add `setuptools` as a requirement.

2024-07-12 18:16 UTC, fabclmnt requested changes
Hi @abdrysdale ,

thank you for your contribution. Nevertheless, it is odd that installing the `setuptools` is the solution for the issue. The behaviour that you are getting seems to be related with something more as we are not being able to replicate. 

Here is a screenshot of a conda environment that I've just created and where I've installed ydata-profiling. 

![image](https://github.com/user-attachments/assets/27f4c842-e7e0-4e6e-949e-7d61085620e8)

I would prefer to avoid adding the dependency to `setuptools` given this is something that is only needed to be installed in case you are building python yourself. 

I would put it as something optional in case the user is aware it is missing it in its environment.

2024-07-12 18:17 UTC, fabclmnt commented
Also, can you please make sure that your PR follows the naming and convention so that we are able to build the versions of the package automatically (eg. fix: (message), feat: (message), etc.)

2024-07-16 09:30 UTC, abdrysdale commented
I've managed to confirm this on my Windows PC by running the following:

```python

def test():

    # Ensure setuptools has not been installed alongside ydata_profiling
    try:
        import setuptools
        print("Setup tools was already installed - it shouldn't be!")
        assert False
        
    except ModuleNotFoundError as exception:
        assert str(exception) == "No module named 'setuptools'"

    # This fails with: ModuleNotFoundError: No module named 'pkg_resources'
    import ydata_profiling
        

if __name__ == "__main__":
    test()
```

Which fails with:

```
  File "C:\Users\foo\AppData\Local\pypoetry\Cache\virtualenvs\ydata-test-w9_z196s-py3.12\Lib\site-packages\ydata_profiling\profile_report.py", line 9, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```

2024-07-16 09:37 UTC, abdrysdale commented
> Nevertheless, it is odd that installing the setuptools is the solution for the issue

How so? `pkg_resources` is part of `setuptools` (https://setuptools.pypa.io/en/latest/pkg_resources.html) so if `setuptools` isn't installed then `pkg_resources` won't be installed.

Can you confirm that `setuptools` isn't installed globally or elsewhere and that's why you're not getting the same error? Have you tried in a VM?

2024-11-15 10:33 UTC, jklaise commented
@fabclmnt I suggest reproducing using a Python 3.12 venv as from Python 3.12 `setuptools` is no longer bundled, see https://docs.python.org/3/whatsnew/3.12.html:
> [gh-95299](https://github.com/python/cpython/issues/95299): Do not pre-install setuptools in virtual environments created with [venv](https://docs.python.org/3/library/venv.html#module-venv). This means that distutils, setuptools, pkg_resources, and easy_install will no longer available by default; to access these run pip install setuptools in the [activated](https://docs.python.org/3/library/venv.html#venv-explanation) virtual environment.

Note that conda virtual envs might still bundle setuptools so the issue might not be apparent if using conda with Python 3.12. In short, imo adding `setuptools` as an explicit dependency for `python>=3.12` seems to be the right solution until the library migrates from `pkg_resources` to `importlib.resources`.

2025-02-03 22:08 UTC, CesarArroyo09 commented
Please accept this and close/reject #1698.

As explained by @ssiegel in #1698, if something from `setuptools` is used within the library and we already know that there are some environments where `setuptools` is not present by default then `setuptools` should be added as an explicit dependence of the package.

2025-02-03 22:12 UTC, CesarArroyo09 commented
I also noticed there is not `pyproject.toml` file in this project and it stills support Python versions that reached end-of-life. I would volunteer in upgrading the package management if I somebody would guide me through the process (as with feedback).

Anyway, great project and I hope it still has a lot of life ahead.

2025-03-03 22:23 UTC, fabclmnt commented
Hi @CesarArroyo09,

Thank you for taking the initiative! However, that action has [already been addressed by another community member](https://github.com/ydataai/ydata-profiling/pull/1448). While our team hasn't had the chance to review it yet due to time constraints, it will be merged in the next release.

Regarding _setuptools_, as mentioned previously, it is not required during ydata-profiling runtime, so I would not include it in the requirements for several reasons:
- Unnecessary in Many Environments – Many Python environments (e.g., venv, pipx) already install _setuptools_ automatically, making its inclusion redundant.
- Potential Version Conflicts – Specifying setuptools as a dependency could introduce compatibility issues, especially if a specific version is required.
- Additionally, since pyproject.toml has been in our backlog and is already in development, I don’t see the changes in this PR as necessary.

Thanks again for your contributions, and whenever you fell like contributing feel free to do so, the team will be happy to guide ans support you through the process.

2025-03-04 23:49 UTC, fabclmnt commented
Solved by #1711

2025-03-04 23:49 UTC, fabclmnt commented
Not needed. Issue reported solved by #1711

2025-03-04 23:49 UTC, fabclmnt commented
Not needed. Issue reported solved by https://github.com/ydataai/ydata-profiling/pull/1711

2025-03-04 23:50 UTC, fabclmnt commented
Not needed. Issue reported solved by #1711

2025-03-04 23:50 UTC, closed without merging

2025-04-07 09:50 UTC, abdrysdale commented
> Regarding _setuptools_, as mentioned previously, it is not required during ydata-profiling runtime, so I would not include it in the requirements for several reasons:

It is required in runtime. I'm not, nor are other people with this issue, building Python from source. This fails when trying to import the module.
 
> * Unnecessary in Many Environments – Many Python environments (e.g., venv, pipx) already install _setuptools_ automatically, making its inclusion redundant.

Just because a few (even many) Python environments bundle setuptools doesn't mean the inclusion should be redundant. By nature of not including setuptools in the requirements they are no longer requirements.

> * Potential Version Conflicts – Specifying setuptools as a dependency could introduce compatibility issues, especially if a specific version is required.

Good dependency managers (such as poetry or uv) handle this for you. Testing will tell you what range of values are acceptable for your project and then if others have compatibility issues then these are indeed compatibility issues as both projects require different versions of setuptools. This package requires setuptools, you're just not specifying it in the requirements which doesn't solve the underlying issue.
 
> * Additionally, since pyproject.toml has been in our backlog and is already in development, I don’t see the changes in this PR as necessary.

setuptools can be added to the dependencies specified by the pyproject.toml file. Better yet would be to move to importlib.resources

2026-03-25 17:57 UTC, gsouf commented
works on python 3.11. Broken on 3.12+