fix: updated scipy version to allow 1.14.x
ydataai/ydata-profiling pull request #1666
Opened 2024-10-25 18:59 UTC by ankana2113

Updated `requirements.txt` to support Scipy versions 1.14.x

closes : #1648

2024-10-25 20:08 UTC, ankana2113 commented
@melanopsis would you please review this PR?

2024-10-28 17:39 UTC, fabclmnt requested changes
Hi @ankana2113 ,

thank you for your contribution! Nevertheless, your PR messages do not comply with the expected naming and convention. Can you please update the history of your commits to align with fix: (description) or feat: (description).

2024-10-29 03:09 UTC, ankana2113 commented
@fabclmnt would you please check if the changes done are alright?

2024-10-29 15:54 UTC, fabclmnt commented
Hi @ankana2113, 

I've forced the required change this time. Instead of the previous commit message "updated spicy ..." I've insured the expected naming and convention "fix: updated spicy...". 

I hope this was an incentive to keep contributing to Ydata-profiling! Thank you 🚀

2025-01-29 22:11 UTC, closed without merging